### ISSUE TITLE
Session sharing is not working

### ISSUE THREAD

**Issue by urtson** [geocollections/eurocore-db-ui#46]
The user cannot be simultaneously logged in into portal/API or admin interface. Logging into portal and then clicking Manage data logs the user into admin interface but logs out from API. This happens in both directions.
Similar setup works in upload.geocollections, rwapi and rwapi admin

**Comment by enmust** [comment]
I didn't know if this issue was for me but app login code is both the same.

if you log in from the api and then log in from the admin interface then it logs out from the api also vice versa. 

Basically you can't be simultaneously logged in in API and admin interface because app just sends login request which logs you into API.
