### ISSUE TITLE
Selecting a method should deselect default parameters

### ISSUE THREAD

**Issue by urtson** [geocollections/eurocore-db-ui#54]
https://eurocore.rocks/#/drillcore_data/4
https://eurocore.rocks/#/drillcore_data/1

**Comment by enmust** [comment]
Can you give more information because currently it seems to work, for example if you press 'select XRF' then it selects all XRF-s and then you have a possibility to 'Deselect XRF'. 

If you are thinking that when you select, for example all XRF-s and then leave and come back to the same page and see that all XRF-s are selected but button still says 'select XRF' instead of 'deselect XRF' then yes that should be fixed.

**Comment by urtson** [comment]
Currently Ni, Cu, Pd, Pt of different methods (ICP-OES, ICP-MS, GF-AAS, XRF) are selected by default. If I click 'Select XRF', only XRF parameters should be selected and all other parameters (ICP-OES, ICP-MS, GF-AAS) should be deselected as I want to see only XRF data.

Yes, the issue of remembering the choice must be fixed too.

**Comment by enmust** [comment]
Then there will be no way to see different methods simultaneously, only by selecting manually one by one.

**Comment by enmust** [comment]
Works as requested
